name: Deployment to Production Server

on:
  push:
    branches:
      - main  # Only run on pushes to the main branch

jobs:
  build:
    timeout-minutes: 60
    runs-on: ubuntu-latest

    steps:
      - name: Check E2E Test Status
        run: exit 0 # Placeholder for checking test status

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'  # Use the appropriate PHP version for Laravel
          extensions: |
              - mbstring
              - pdo
              - pdo_mysql
              - bcmath
              - xml
              - curl
              - json
              - openssl
              - gd
              - zip
              - tokenizer
              - ctype
              - dom
              - simplexml
              - xmlreader
              - xmlwriter
              - zlib
          coverage: none

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      - name: Select the proper .env file
        run: mv .env.prod .env  # Make sure you're using the production environment file

      - name: Install Node.js dependencies
        run: npm install

      - name: Update Composer dependencies
        run: composer update --no-dev --prefer-dist --optimize-autoloader  # Only install production dependencies

      - name: Install Composer dependencies
        run: composer install --no-dev --prefer-dist --optimize-autoloader  # Ensure production dependencies

      - name: Set up Laravel environment
        run: |
          php artisan key:generate
          php artisan config:cache
          php artisan route:cache
          php artisan view:cache

      - name: Deploy to Server
        uses: easingthemes/ssh-deploy@main
        with:
          SSH_PRIVATE_KEY: ${{ secrets.DEV_SERVER_SSH_PRIVATE_KEY }}
          ARGS: "-rlgoDzc --delete"
          SOURCE: "./"
          REMOTE_HOST: ${{ vars.REMOTE_HOST }}
          REMOTE_USER: "gitactions"
          TARGET: "/var/www/misana/dev/stage"  # Ensure you're deploying to the correct production folder
          EXCLUDE: "--exclude=node_modules --exclude=vendor"  # Exclude non-essential folders

      - name: Configure SSH on server for remote commands
        run: |
          mkdir -p ~/.ssh/
          echo "${{ secrets.DEV_SERVER_SSH_PRIVATE_KEY }}" > ~/.ssh/authorized_keys
          chmod 600 ~/.ssh/authorized_keys
          cat >>~/.ssh/config <<END
          Host production
            HostName ${{ vars.REMOTE_HOST }}
            User "gitactions"
            IdentityFile ~/.ssh/authorized_keys
            StrictHostKeyChecking no
          END

      - name: Check PHP Extensions on Server
        run: ssh production 'php -m | grep -E "gd|mbstring|pdo_mysql|bcmath|xml|curl|json|openssl|zip|tokenizer|ctype|dom|simplexml|xmlreader|xmlwriter|zlib"'

      - name: Update Composer on the server
        run: ssh production 'cd /var/www/misana/dev/stage && composer update --no-dev --prefer-dist --optimize-autoloader'
        continue-on-error: true

      - name: Clear old files and caches
        run: |
          ssh production 'rm -rf /var/www/misana/dev/stage/node_modules'
        continue-on-error: true

      - name: Install Composer on the server
        run: ssh production 'cd /var/www/misana/dev/stage && composer install --no-dev --prefer-dist --optimize-autoloader'
        continue-on-error: true

      - name: Run npm install and build assets
        run: ssh production 'cd /var/www/misana/dev/stage && npm install && npm run prod'
        continue-on-error: true

      - name: Clear Laravel caches
        run: ssh production 'cd /var/www/misana/dev/stage && php artisan config:cache && php artisan route:cache && php artisan view:cache'

      - name: Stop PM2 (if necessary)
        run: ssh production 'pm2 stop misana'
        continue-on-error: true

      - name: Delete old PM2 instance (if necessary)
        run: ssh production 'pm2 delete misana'
        continue-on-error: true

      - name: Start Laravel application with PM2 in production mode
        run: ssh production 'cd /var/www/misana/dev/stage && pm2 start "php artisan serve --host=127.0.0.1 --port=3018" --name "misana" --log "/home/gitactions/.pm2/logs/misana-error.log" --env=production'
        continue-on-error: true
